-- Add FK constraints
ALTER TABLE  WF_COUNTRIES ADD CONSTRAINT "WF_REGION_ID_FK1" FOREIGN KEY ("REGION_ID")
	REFERENCES  WF_WORLD_REGIONS ("REGION_ID") ENABLE;

CREATE INDEX  "WF_CTRY_REG_IDX" ON  WF_COUNTRIES ("REGION_ID");

ALTER TABLE  WF_COUNTRIES ADD CONSTRAINT "WF_CURR_ID_FK2" FOREIGN KEY ("CURRENCY_CODE")
	REFERENCES  WF_CURRENCIES ("CURRENCY_CODE") ENABLE;

CREATE INDEX  "WF_CTRY_CURR_IDX" ON  WF_COUNTRIES ("CURRENCY_CODE");
