-- Create wf_spoken_languages table
CREATE TABLE  WF_SPOKEN_LANGUAGES
   ("COUNTRY_ID" NUMBER(4,0), 
	"LANGUAGE_ID" NUMBER(4,0), 
	"OFFICIAL" VARCHAR2(2), 
	"COMMENTS" VARCHAR2(512), 
	CONSTRAINT "WF_SPOKEN_LANG_PK" PRIMARY KEY ("COUNTRY_ID", "LANGUAGE_ID")
	USING INDEX  ENABLE
   );
-- Add FK constraints
ALTER TABLE  WF_SPOKEN_LANGUAGES ADD CONSTRAINT "WF_CTRY_NUM_FK1" FOREIGN KEY ("COUNTRY_ID")
	REFERENCES  WF_COUNTRIES ("COUNTRY_ID") ENABLE;

ALTER TABLE  WF_SPOKEN_LANGUAGES ADD CONSTRAINT "WF_LANG_ID_FK" FOREIGN KEY ("LANGUAGE_ID")
	REFERENCES  WF_LANGUAGES ("LANGUAGE_ID") ENABLE;
	