--Create wf_world_regions table
CREATE TABLE  WF_WORLD_REGIONS
   ("REGION_ID" NUMBER(3,0), 
	"REGION_NAME" VARCHAR2(35) CONSTRAINT "WF_REG_REGNAME_NN" NOT NULL ENABLE, 
	CONSTRAINT "WF_REG_PK" PRIMARY KEY ("REGION_ID")
	USING INDEX  ENABLE
   );