-- Create wf_countries table
CREATE TABLE  WF_COUNTRIES
   ("COUNTRY_ID" NUMBER(4,0), 
	"REGION_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(70) CONSTRAINT "WF_CNAME_NN" NOT NULL ENABLE, 
	"COUNTRY_TRANSLATED_NAME" VARCHAR2(40), 
	"LOCATION" VARCHAR2(90), 
	"CAPITOL" VARCHAR2(50), 
	"AREA" NUMBER(15,0), 
	"COASTLINE" NUMBER(8,0), 
	"LOWEST_ELEVATION" NUMBER(6,0), 
	"LOWEST_ELEV_NAME" VARCHAR2(70), 
	"HIGHEST_ELEVATION" NUMBER(6,0), 
	"HIGHEST_ELEV_NAME" VARCHAR2(50), 
	"DATE_OF_INDEPENDENCE" VARCHAR2(30), 
	"NATIONAL_HOLIDAY_NAME" VARCHAR2(200), 
	"NATIONAL_HOLIDAY_DATE" VARCHAR2(30), 
	"POPULATION" NUMBER(12,0), 
	"POPULATION_GROWTH_RATE" VARCHAR2(10), 
	"LIFE_EXPECT_AT_BIRTH" NUMBER(6,2), 
	"MEDIAN_AGE" NUMBER(6,2), 
	"AIRPORTS" NUMBER(6,0), 
	"CLIMATE" VARCHAR2(1000), 
	"FIPS_ID" CHAR(2), 
	"INTERNET_EXTENSION" VARCHAR2(3), 
	"FLAG" BLOB, 
	"CURRENCY_CODE" VARCHAR2(7) NOT NULL ENABLE, 
	CONSTRAINT "WF_CRTY_PK" PRIMARY KEY ("COUNTRY_ID")
	USING INDEX  ENABLE
   );
   