--Create wf_currencies table
CREATE TABLE  WF_CURRENCIES 
   ("CURRENCY_CODE" VARCHAR2(7), 
	"CURRENCY_NAME" VARCHAR2(40) CONSTRAINT "WF_CURR_NN" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(150), 
	CONSTRAINT "WF_CURR_PK" PRIMARY KEY ("CURRENCY_CODE")
	USING INDEX  ENABLE
   );