CREATE TABLE  "D_CDS"
   ("CD_NUMBER" NUMBER(5,0),
    "TITLE" VARCHAR2(50) CONSTRAINT "D_CDS_TITLE_NN" NOT NULL ENABLE,
    "PRODUCER" VARCHAR2(50) CONSTRAINT "D_CDS_PRODUCER_NN" NOT NULL ENABLE,
    "YEAR" VARCHAR2(4) CONSTRAINT "D_CDS_YEAR_NN" NOT NULL ENABLE,
     CONSTRAINT "D_CDS_CD_NUMBER_PK" PRIMARY KEY ("CD_NUMBER")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_CLIENTS"
   ("CLIENT_NUMBER" NUMBER(5,0),
    "FIRST_NAME" VARCHAR2(25) CONSTRAINT "D_CLT_FIST_NAME_NN" NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(30) CONSTRAINT "D_CLT_LAST_NAME_NN" NOT NULL ENABLE,
    "PHONE" NUMBER(15,0) CONSTRAINT "D_CLT_PHONE_NN" NOT NULL ENABLE,
    "EMAIL" VARCHAR2(50),
     CONSTRAINT "D_CLT_CLIENT_NUMBER_PK" PRIMARY KEY ("CLIENT_NUMBER")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_PACKAGES"
   ("CODE" NUMBER(10,0),
    "LOW_RANGE" NUMBER(6,0) CONSTRAINT "D_PKE_LOW_RANGE_NN" NOT NULL ENABLE,
    "HIGH_RANGE" NUMBER(6,0) CONSTRAINT "D_PKE_HIGH_RANGE_NN" NOT NULL ENABLE,
     CONSTRAINT "D_PKE_CODE_PK" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_THEMES"
   ("CODE" NUMBER(10,0),
    "DESCRIPTION" VARCHAR2(100) CONSTRAINT "D_TME_DESC_NN" NOT NULL ENABLE,
     CONSTRAINT "D_TME_CODE_PK" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_VENUES"
   ("ID" NUMBER(5,0),
    "LOC_TYPE" VARCHAR2(30) CONSTRAINT "D_VNE_LOC_TYPE_NN" NOT NULL ENABLE,
    "ADDRESS" VARCHAR2(100) CONSTRAINT "D_VNE_ADDRESS_NN" NOT NULL ENABLE,
    "RENTAL_FEE" VARCHAR2(50) CONSTRAINT "D_VNE_RENTAL_FEE_NN" NOT NULL ENABLE,
    "COMMENTS" VARCHAR2(100),
     CONSTRAINT "D_VNE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_EVENTS"
   ("ID" NUMBER(5,0),
    "NAME" VARCHAR2(50) CONSTRAINT "D_EVE_NAME_NN" NOT NULL ENABLE,
    "EVENT_DATE" DATE CONSTRAINT "D_EVE_EVENT_DATE_NN" NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(50),
    "COST" NUMBER(8,2) CONSTRAINT "D_EVE_COST_NN" NOT NULL ENABLE,
    "VENUE_ID" NUMBER(5,0) CONSTRAINT "D_EVE_VENUE_ID_NN" NOT NULL ENABLE,
    "PACKAGE_CODE" NUMBER(5,0) CONSTRAINT "D_EVE_PACKAGE_CODE_NN" NOT NULL ENABLE,
    "THEME_CODE" NUMBER(10,0) CONSTRAINT "D_EVE_THEME_CODE_NN" NOT NULL ENABLE,
    "CLIENT_NUMBER" NUMBER(5,0) CONSTRAINT "D_EVE_CLIENT_NUMBER_NN" NOT NULL ENABLE,
     CONSTRAINT "D_EVE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_PARTNERS"
   ("ID" NUMBER(5,0),
    "FIRST_NAME" VARCHAR2(25) CONSTRAINT "D_PTR_FIRST_NAME_NN" NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(30) CONSTRAINT "D_PTR_LAST_NAME_NN" NOT NULL ENABLE,
    "EXPERTISE" VARCHAR2(25),
    "SPECIALTY" VARCHAR2(25),
    "AUTH_EXPENSE_AMT" NUMBER(8,2),
    "MANAGER_ID" NUMBER(5,0),
    "PARTNER_TYPE" VARCHAR2(25) CONSTRAINT "D_PTR_PARTNER_TYPE_NN" NOT NULL ENABLE,
     CONSTRAINT "D_PTR_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_JOB_ASSIGNMENTS"
   ("PARTNER_ID" NUMBER(5,0),
    "EVENT_ID" NUMBER(5,0),
    "JOB_DATE" DATE CONSTRAINT "D_JAT_JOB_DATE_NN" NOT NULL ENABLE,
    "STATUS" VARCHAR2(50),
     CONSTRAINT "D_JAT_PK" PRIMARY KEY ("PARTNER_ID", "EVENT_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_TYPES"
   ("CODE" NUMBER(10,0),
    "DESCRIPTION" VARCHAR2(50) CONSTRAINT "D_TPE_DESC_NN" NOT NULL ENABLE,
     CONSTRAINT "D_TPE_CODE_PK" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_SONGS"
   ("ID" NUMBER(5,0),
    "TITLE" VARCHAR2(50) CONSTRAINT "D_SNG_TITLE_NN" NOT NULL ENABLE,
    "DURATION" VARCHAR2(20),
    "ARTIST" VARCHAR2(20),
    "TYPE_CODE" NUMBER(5,0) CONSTRAINT "D_SNG_TYPE_CODE_NN" NOT NULL ENABLE,
     CONSTRAINT "D_SNG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_PLAY_LIST_ITEMS"
   ("EVENT_ID" NUMBER(5,0),
    "SONG_ID" NUMBER(5,0),
    "COMMENTS" VARCHAR2(80),
     CONSTRAINT "D_PLM_PK" PRIMARY KEY ("EVENT_ID", "SONG_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE  "D_TRACK_LISTINGS"
   ("SONG_ID" NUMBER(5,0),
    "CD_NUMBER" NUMBER(5,0),
    "TRACK" NUMBER(2,0) CONSTRAINT "D_TLG_TRACK_NUMBER_NN" NOT NULL ENABLE,
     CONSTRAINT "D_TLG_PK" PRIMARY KEY ("SONG_ID", "CD_NUMBER")
  USING INDEX  ENABLE
   );

ALTER TABLE  "D_EVENTS" ADD CONSTRAINT "D_EVE_CLIENT_NUMBER_FK" FOREIGN KEY ("CLIENT_NUMBER")
      REFERENCES  "D_CLIENTS" ("CLIENT_NUMBER") ENABLE;
ALTER TABLE  "D_EVENTS" ADD CONSTRAINT "D_EVE_PACKAGE_CODE_FK" FOREIGN KEY ("PACKAGE_CODE")
      REFERENCES  "D_PACKAGES" ("CODE") ENABLE;
ALTER TABLE  "D_EVENTS" ADD CONSTRAINT "D_EVE_THEME_CODE_FK" FOREIGN KEY ("THEME_CODE")
      REFERENCES  "D_THEMES" ("CODE") ENABLE;
ALTER TABLE  "D_EVENTS" ADD CONSTRAINT "D_EVE_VENUE_ID_FK" FOREIGN KEY ("VENUE_ID")
      REFERENCES  "D_VENUES" ("ID") ENABLE;
ALTER TABLE  "D_JOB_ASSIGNMENTS" ADD CONSTRAINT "D_JAT_EVENT_ID_FK" FOREIGN KEY ("EVENT_ID")
      REFERENCES  "D_EVENTS" ("ID") ENABLE;
ALTER TABLE  "D_JOB_ASSIGNMENTS" ADD CONSTRAINT "D_JAT_PARTNER_ID_FK" FOREIGN KEY ("PARTNER_ID")
      REFERENCES  "D_PARTNERS" ("ID") ENABLE;
ALTER TABLE  "D_PLAY_LIST_ITEMS" ADD CONSTRAINT "D_PLM_EVENT_ID_FK" FOREIGN KEY ("EVENT_ID")
      REFERENCES  "D_EVENTS" ("ID") ENABLE;
ALTER TABLE  "D_PLAY_LIST_ITEMS" ADD CONSTRAINT "D_PLM_SONG_ID_FK" FOREIGN KEY ("SONG_ID")
      REFERENCES  "D_SONGS" ("ID") ENABLE;
ALTER TABLE  "D_SONGS" ADD CONSTRAINT "D_SNG_TYPE_CODE_FK" FOREIGN KEY ("TYPE_CODE")
      REFERENCES  "D_TYPES" ("CODE") ENABLE;
ALTER TABLE  "D_TRACK_LISTINGS" ADD CONSTRAINT "D_TLG_CD_NUMBER_FK" FOREIGN KEY ("CD_NUMBER")
      REFERENCES  "D_CDS" ("CD_NUMBER") ENABLE;
ALTER TABLE  "D_TRACK_LISTINGS" ADD CONSTRAINT "D_TLG_SONG_ID_FK" FOREIGN KEY ("SONG_ID")
      REFERENCES  "D_SONGS" ("ID") ENABLE;

CREATE INDEX  "D_CDS_IDX" ON  "D_CDS" ("TITLE");
CREATE INDEX  "SONG_ID_IDX" ON  "D_TRACK_LISTINGS" ("SONG_ID");
